# -- Config Consul server -- #
---
- hosts: 192.168.14.245
  remote_user: bot
  sudo: yes
  tasks:
   - name: Create consul container
 docker_container:
   name: consul
   ports:
          - "8400:8400"
          - "8500:8500/tcp"
          - "8600:53/udp"
   env:
        CONSUL_LOCAL_CONFIG={"acl_datacenter":"Cluster-Infra-Prod","acl_default_policy":"deny","acl_down_policy":"extend-cache","acl_master_token":"Passw0rd","bootstrap_expect":1,"datacenter":"Cluster-Infra-Prod","data_dir":"/usr/local/bin/consul.d/data","server":true}
   
   command:
      -retry-join"127.0.0.1" consul agent
      -server 
      -bind=127.0.0.1 
      -client=0.0.0.0 
      -ui


#docker run -d --name=consul -p 8400:8400 -p 8500:8500/tcp -p 8600:53/udp -e 'CONSUL_LOCAL_CONFIG={"acl_datacenter":"Cluster-Infra-Prod","acl_default_policy":"deny","acl_down_policy":"extend-cache","acl_master_token":"Passw0rd","bootstrap_expect":1,"datacenter":"Cluster-Infra-Prod","data_dir":"/usr/local/bin/consul.d/data","server":true}' -retry-join"127.0.0.1" consul agent -server -bind=127.0.0.1 -client=0.0.0.0 -ui
