influxdb:
  image: influxdb:1.1
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"

telegraf:
  image: telegraf:1.1
  container_name: telegraf
  links:
    - influxdb

chronograf:
  image: chronograf:1.0.0-rc1
  container_name: chronograf
  ports:
    - "10000:10000"
  links:
    - influxdb

kapacitor:
  image: kapacitor:1.1
  container_name: kapacitor
  ports: 9092
  links:
    - influxdb
